---
title: "Airbnb Data from 2017"
output: 
  flexdashboard::flex_dashboard:
    theme: journal
    social: menu
    orientation: rows
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(leaflet)

data("nyc_airbnb")

nyc_airbnb_1 = 
  nyc_airbnb %>% 
    mutate(
      rating = review_scores_location / 2) %>% 
    select(neighbourhood_group, neighbourhood, rating, price, room_type, 
           lat, long) %>% 
  filter(neighbourhood_group == "Manhattan",
         price %in% 100:500,
         room_type == "Entire home/apt") %>% 
  drop_na(rating)

nyc_airbnb_2 =
  nyc_airbnb %>% 
    mutate(rating = review_scores_location / 2) %>% 
    select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>% 
  filter(price %in% 100:500,
         room_type == "Entire home/apt") %>% 
  drop_na(rating) 
```

Row {data-width=1000}
-----------------------------------------------------------------------
### Map with Ratings

```{r}
pal = colorNumeric("magma", nyc_airbnb_2 %>% pull(rating))

nyc_airbnb_2 %>% 
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(~lat, ~long, radius = 0.5, color = ~pal(rating))
```

Row {data-width=1000}
-----------------------------------------------------------------------

### Price Scatterplot

```{r}
nyc_airbnb_1 %>% 
  mutate(
    text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  plot_ly(x = ~lat, y = ~long, color = ~price, text = ~text_label, alpha = 0.5, type = "scatter", mode = "markers") 
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Price Boxplot

```{r}
nyc_airbnb_1 %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, x = ~neighbourhood, color = ~neighbourhood,
          type = "box", colors = "viridis")
```

### Count Boxplot

```{r}
nyc_airbnb_1 %>% 
  count(neighbourhood) %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```
